apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-app
data:
  DB_HOST: database
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_DATABASE: devops_lessons
  PORT: "7000"
  HOST: "0.0.0.0"
  APP_NAME: Lessons
  APP_DESCRIPTION: Devops lessons REST API
  NODE_ENV: development

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devops-app
type: Opaque
stringData:
  DB_PASSWORD: root

